// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwktlguuqdeiecmfszhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3a3RsZ3V1cWRlaWVjbWZzemhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxMTIxNzMsImV4cCI6MjA4ODY4ODE3M30.g_bfzx_Uz_Iyq83jzlVbsiQQNTXMwCMSAc78Ir2eeGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});