"""
Ask command - open-ended question against the investigation graph.
"""
from __future__ import annotations

from typing import Optional

import anyio
import typer

from bugpilot.context import AppContext
from bugpilot.output.human import console, print_error
from bugpilot.output.json_out import print_json
from bugpilot.session import APIError, api_post_analysis

app = typer.Typer(help="Ask an open-ended question about the current investigation")


def _get_ctx(typer_ctx: typer.Context) -> AppContext:
    ctx: AppContext = typer_ctx.obj
    if not ctx.load_credentials():
        print_error("Not authenticated. Run: bugpilot auth activate")
        raise typer.Exit(1)
    return ctx


@app.callback(invoke_without_command=True)
def cmd_ask(
    ctx: typer.Context,
    question: str = typer.Argument(..., help='Question to ask, e.g. "What changed before the spike?"'),
    investigation_id: Optional[str] = typer.Option(
        None, "--investigation", "-i", help="Investigation ID (uses stored context if omitted)"
    ),
) -> None:
    """Ask an open-ended question about the investigation graph. Powered by LLM synthesis."""
    app_ctx = _get_ctx(ctx)

    inv_id = app_ctx.resolve_investigation_id(investigation_id)
    if not inv_id:
        print_error(
            "No investigation context set. Use --investigation <id> or run: bugpilot incident open <id>"
        )
        raise typer.Exit(1)

    async def _run():
        try:
            data = await api_post_analysis(
                app_ctx,
                f"/api/v1/investigations/{inv_id}/ask",
                body={"question": question},
            )
            if app_ctx.output_format == "json":
                print_json(data)
            else:
                from rich.panel import Panel
                answer = data.get("answer") or data.get("text") or str(data)
                console.print(Panel(answer, title=f"[bold]Answer[/bold]", border_style="cyan"))
                model = data.get("model")
                if model:
                    console.print(f"[dim]Generated by: {model}[/dim]")
        except APIError as e:
            print_error(f"Ask failed: {e.detail}")
            raise typer.Exit(1)

    anyio.run(_run)
