"""
Shared export helpers used by both export_cmd and investigation_cmd.
"""
from __future__ import annotations

import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from bugpilot.context import AppContext


async def collect_investigation_bundle(app_ctx: "AppContext", inv_id: str) -> dict:
    """Collect all data for an investigation into a single bundle."""
    from bugpilot.session import api_get
    inv = await api_get(app_ctx, f"/api/v1/investigations/{inv_id}")
    evidence = await api_get(app_ctx, "/api/v1/evidence", params={"investigation_id": inv_id})
    hypotheses = await api_get(app_ctx, "/api/v1/hypotheses", params={"investigation_id": inv_id})
    actions = await api_get(app_ctx, "/api/v1/actions", params={"investigation_id": inv_id})
    timeline = await api_get(app_ctx, "/api/v1/graph/timeline", params={"investigation_id": inv_id})
    return {
        "investigation": inv,
        "evidence": evidence.get("items", []),
        "hypotheses": hypotheses.get("items", []),
        "actions": actions.get("items", []),
        "timeline": timeline.get("events", []),
        "exported_at": datetime.datetime.utcnow().isoformat() + "Z",
        "format_version": "1.0",
    }


def render_markdown(bundle: dict) -> str:
    """Render an investigation bundle as a Markdown incident report."""
    inv = bundle["investigation"]
    lines = [
        f"# Incident Report: {inv.get('title', 'Unknown')}",
        "",
        f"**Status:** {inv.get('status', '-').upper()}",
        f"**Severity:** {inv.get('severity', '-').upper()}",
        f"**Created:** {inv.get('created_at', '-')}",
        f"**Resolved:** {inv.get('resolved_at') or 'Not resolved'}",
        "",
    ]
    if inv.get("symptom"):
        lines += ["## Symptom", "", inv["symptom"], ""]
    if inv.get("description"):
        lines += ["## Description", "", inv["description"], ""]

    timeline = bundle.get("timeline", [])
    if timeline:
        lines += ["## Timeline", ""]
        for e in timeline:
            lines.append(
                f"- **{(e.get('occurred_at') or '-')[:19]}** [{e.get('event_type', '-')}] {e.get('description', '-')}"
            )
        lines.append("")

    evidence = bundle.get("evidence", [])
    if evidence:
        lines += ["## Evidence", ""]
        for ev in evidence:
            lines.append(f"- **{ev.get('kind', '-')}** — {ev.get('label', '-')}")
            if ev.get("summary"):
                lines.append(f"  > {ev['summary']}")
        lines.append("")

    hypotheses = bundle.get("hypotheses", [])
    if hypotheses:
        lines += ["## Hypotheses", ""]
        for h in hypotheses:
            conf = h.get("confidence_score")
            conf_str = f" ({conf:.0%} confidence)" if conf is not None else ""
            lines.append(f"- [{h.get('status', '-').upper()}] **{h.get('title', '-')}**{conf_str}")
            if h.get("reasoning"):
                lines.append(f"  > {h['reasoning']}")
        lines.append("")

    actions = bundle.get("actions", [])
    if actions:
        lines += ["## Actions", ""]
        for a in actions:
            lines.append(
                f"- [{a.get('status', '-').upper()}] **{a.get('title', '-')}** "
                f"(risk: {a.get('risk_level', '-')})"
            )
        lines.append("")

    lines += ["---", f"*Generated by BugPilot at {bundle.get('exported_at', '')}*"]
    return "\n".join(lines)
