"""
Investigation export command - export investigation data (JSON or Markdown).
Implements: bugpilot investigation export --format [json|markdown]
"""
from __future__ import annotations

import json as json_mod
from pathlib import Path
from typing import Optional

import anyio
import typer

from bugpilot.context import AppContext
from bugpilot.output.human import console, print_error, print_success
from bugpilot.output.json_out import print_json
from bugpilot.session import APIError, api_get

app = typer.Typer(help="Investigation export and management")


def _get_ctx(typer_ctx: typer.Context) -> AppContext:
    ctx: AppContext = typer_ctx.obj
    if not ctx.load_credentials():
        print_error("Not authenticated. Run: bugpilot auth activate")
        raise typer.Exit(1)
    return ctx


async def _collect_bundle(app_ctx: AppContext, inv_id: str) -> dict:
    import datetime
    inv = await api_get(app_ctx, f"/api/v1/investigations/{inv_id}")
    evidence = await api_get(app_ctx, "/api/v1/evidence", params={"investigation_id": inv_id})
    hypotheses = await api_get(app_ctx, "/api/v1/hypotheses", params={"investigation_id": inv_id})
    actions = await api_get(app_ctx, "/api/v1/actions", params={"investigation_id": inv_id})
    timeline = await api_get(app_ctx, "/api/v1/graph/timeline", params={"investigation_id": inv_id})
    return {
        "investigation": inv,
        "evidence": evidence.get("items", []),
        "hypotheses": hypotheses.get("items", []),
        "actions": actions.get("items", []),
        "timeline": timeline.get("events", []),
        "exported_at": datetime.datetime.utcnow().isoformat() + "Z",
        "format_version": "1.0",
    }


def _render_markdown(bundle: dict) -> str:
    inv = bundle["investigation"]
    lines = [
        f"# Incident Report: {inv.get('title', 'Unknown')}",
        "",
        f"**Status:** {inv.get('status', '-').upper()}",
        f"**Severity:** {inv.get('severity', '-').upper()}",
        f"**Created:** {inv.get('created_at', '-')}",
        f"**Resolved:** {inv.get('resolved_at') or 'Not resolved'}",
        "",
    ]
    if inv.get("symptom"):
        lines += ["## Symptom", "", inv["symptom"], ""]
    if inv.get("description"):
        lines += ["## Description", "", inv["description"], ""]
    timeline = bundle.get("timeline", [])
    if timeline:
        lines += ["## Timeline", ""]
        for e in timeline:
            lines.append(
                f"- **{(e.get('occurred_at') or '-')[:19]}** [{e.get('event_type', '-')}] {e.get('description', '-')}"
            )
        lines.append("")
    evidence = bundle.get("evidence", [])
    if evidence:
        lines += ["## Evidence", ""]
        for ev in evidence:
            lines.append(f"- **{ev.get('kind', '-')}** — {ev.get('label', '-')}")
            if ev.get("summary"):
                lines.append(f"  > {ev['summary']}")
        lines.append("")
    hypotheses = bundle.get("hypotheses", [])
    if hypotheses:
        lines += ["## Hypotheses", ""]
        for h in hypotheses:
            conf = h.get("confidence_score")
            conf_str = f" ({conf:.0%} confidence)" if conf is not None else ""
            lines.append(f"- [{h.get('status', '-').upper()}] **{h.get('title', '-')}**{conf_str}")
            if h.get("reasoning"):
                lines.append(f"  > {h['reasoning']}")
        lines.append("")
    actions = bundle.get("actions", [])
    if actions:
        lines += ["## Actions", ""]
        for a in actions:
            lines.append(
                f"- [{a.get('status', '-').upper()}] **{a.get('title', '-')}** "
                f"(risk: {a.get('risk_level', '-')})"
            )
        lines.append("")
    lines += ["---", f"*Generated by BugPilot at {bundle.get('exported_at', '')}*"]
    return "\n".join(lines)


@app.command("export")
def cmd_export(
    ctx: typer.Context,
    investigation_id: Optional[str] = typer.Option(
        None, "--investigation", "-i", help="Investigation ID (uses stored context if omitted)"
    ),
    fmt: str = typer.Option("json", "--format", "-f", help="Export format: json|markdown"),
    output: Optional[Path] = typer.Option(None, "--output", "-o", help="Output file (default: stdout)"),
) -> None:
    """Export a full investigation report as JSON or Markdown."""
    app_ctx = _get_ctx(ctx)

    inv_id = app_ctx.resolve_investigation_id(investigation_id)
    if not inv_id:
        print_error(
            "No investigation context set. Use --investigation <id> or run: bugpilot incident open <id>"
        )
        raise typer.Exit(1)

    if fmt not in ("json", "markdown"):
        print_error("--format must be json or markdown")
        raise typer.Exit(1)

    async def _run():
        try:
            bundle = await _collect_bundle(app_ctx, inv_id)
            if fmt == "json":
                content = json_mod.dumps(bundle, indent=2, default=str)
            else:
                content = _render_markdown(bundle)

            if output:
                output.write_text(content)
                print_success(f"Exported to {output}")
            else:
                print(content)
        except APIError as e:
            print_error(f"Export failed: {e.detail}")
            raise typer.Exit(1)

    anyio.run(_run)
