"""
Summary command - LLM-generated summary of the current investigation.
"""
from __future__ import annotations

from typing import Optional

import anyio
import typer

from bugpilot.context import AppContext
from bugpilot.output.human import console, print_error
from bugpilot.output.json_out import print_json
from bugpilot.session import APIError, api_get

app = typer.Typer(help="Show LLM-generated summary of the current investigation", invoke_without_command=True)


def _get_ctx(typer_ctx: typer.Context) -> AppContext:
    ctx: AppContext = typer_ctx.obj
    if not ctx.load_credentials():
        print_error("Not authenticated. Run: bugpilot auth activate")
        raise typer.Exit(1)
    return ctx


@app.callback(invoke_without_command=True)
def cmd_summary(
    ctx: typer.Context,
    investigation_id: Optional[str] = typer.Option(
        None, "--investigation", "-i", help="Investigation ID (uses stored context if omitted)"
    ),
) -> None:
    """Display an LLM-generated summary of the current investigation."""
    app_ctx = _get_ctx(ctx)

    inv_id = app_ctx.resolve_investigation_id(investigation_id)
    if not inv_id:
        print_error(
            "No investigation context set. Use --investigation <id> or run: bugpilot incident open <id>"
        )
        raise typer.Exit(1)

    async def _run():
        try:
            data = await api_get(app_ctx, f"/api/v1/investigations/{inv_id}/summary")
            if app_ctx.output_format == "json":
                print_json(data)
            else:
                from rich.panel import Panel
                summary_text = data.get("summary") or data.get("text") or str(data)
                console.print(
                    Panel(summary_text, title=f"[bold]Investigation Summary[/bold] — {inv_id}", border_style="blue")
                )
                model = data.get("model")
                if model:
                    console.print(f"[dim]Generated by: {model}[/dim]")
        except APIError as e:
            print_error(f"Failed to get summary: {e.detail}")
            raise typer.Exit(1)

    anyio.run(_run)
