"""
Report generation endpoints:

  POST /v1/reports/{investigation_id}          — generate markdown report
  GET  /v1/reports/{investigation_id}/download — download as .md file
  POST /v1/reports/{investigation_id}/confluence — push to Confluence
"""
from __future__ import annotations

import logging
from datetime import datetime
from typing import Optional

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel

from backend.app.database import get_conn, release_conn, set_org_context

log = logging.getLogger(__name__)
router = APIRouter()


class ConfluenceRequest(BaseModel):
    space_key: str
    parent_page_id: Optional[str] = None
    title: Optional[str] = None


def _build_markdown(inv: dict, hypotheses: list) -> str:
    """Build a markdown report from investigation data."""
    lines = []
    lines.append(f"# BugPilot Investigation Report — {inv['id']}")
    lines.append(f"\n**Date:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Status:** {inv['status']}")
    if inv.get("service_name"):
        lines.append(f"**Service:** {inv['service_name']}")
    if inv.get("trigger_ref"):
        lines.append(f"**Trigger:** {inv['trigger_ref']} ({inv.get('trigger_source','')})")
    if inv.get("failure_class"):
        lines.append(f"**Failure class:** {inv['failure_class']}")
    if inv.get("duration_ms"):
        lines.append(f"**Investigation time:** {inv['duration_ms']/1000:.1f}s")

    if inv.get("llm_narrative"):
        lines.append("\n## Summary\n")
        lines.append(inv["llm_narrative"])

    if hypotheses:
        lines.append("\n## Hypotheses\n")
        for h in hypotheses:
            conf = f"{h['confidence']:.0%}" if h.get("confidence") is not None else "N/A"
            lines.append(f"### #{h['rank']} — {h.get('pr_title','Unknown PR')} ({conf} confidence)\n")
            if h.get("pr_url"):
                lines.append(f"- **PR:** [{h['pr_url']}]({h['pr_url']})")
            if h.get("pr_author"):
                lines.append(f"- **Author:** {h['pr_author']}")
            if h.get("pr_merged_at"):
                lines.append(f"- **Merged:** {h['pr_merged_at']}")
            if h.get("file_path"):
                loc = h["file_path"]
                if h.get("line_number"):
                    loc += f":{h['line_number']}"
                lines.append(f"- **Location:** `{loc}`")
            if h.get("diff_type"):
                lines.append(f"- **Change type:** {h['diff_type']}")
            if h.get("narrative"):
                lines.append(f"\n{h['narrative']}\n")
            if h.get("evidence"):
                lines.append("\n**Evidence:**")
                ev = h["evidence"]
                if isinstance(ev, dict):
                    for k, v in ev.items():
                        lines.append(f"- {k}: {v}")
                lines.append("")

    if inv.get("blast_count") is not None:
        lines.append("\n## Blast Radius\n")
        lines.append(f"- **Affected records:** {inv['blast_count']}")
        if inv.get("blast_value_usd"):
            lines.append(f"- **Estimated value at risk:** ${float(inv['blast_value_usd']):,.2f}")
        if inv.get("blast_cohort"):
            lines.append(f"- **Cohort:** {inv['blast_cohort']}")

    feedback = inv.get("feedback")
    if feedback:
        lines.append(f"\n## Feedback\n\n**Verdict:** {feedback}")
        if inv.get("feedback_cause"):
            lines.append(f"**Actual cause:** {inv['feedback_cause']}")

    lines.append(f"\n---\n*Generated by BugPilot — {datetime.utcnow().isoformat()}Z*")
    return "\n".join(lines)


def _fetch_investigation_full(conn, org_id: str, investigation_id: str) -> tuple[dict, list]:
    """Fetch investigation + hypotheses. Returns (inv_dict, hypotheses_list)."""
    with conn.cursor() as cur:
        cur.execute(
            """SELECT id, status, trigger_ref, trigger_source, service_name,
                      failure_class, duration_ms, llm_narrative,
                      blast_count, blast_value_usd, blast_cohort,
                      feedback, feedback_cause
               FROM investigations
               WHERE id = %s AND org_id = %s""",
            (investigation_id, org_id),
        )
        row = cur.fetchone()

    if not row:
        raise HTTPException(status_code=404, detail="Investigation not found")

    inv = {
        "id": row[0], "status": row[1], "trigger_ref": row[2],
        "trigger_source": row[3], "service_name": row[4],
        "failure_class": row[5], "duration_ms": row[6], "llm_narrative": row[7],
        "blast_count": row[8], "blast_value_usd": row[9], "blast_cohort": row[10],
        "feedback": row[11], "feedback_cause": row[12],
    }

    with conn.cursor() as cur:
        cur.execute(
            """SELECT rank, pr_url, pr_title, pr_author, pr_merged_at,
                      file_path, line_number, diff_type, confidence, evidence
               FROM investigation_hypotheses
               WHERE investigation_id = %s ORDER BY rank""",
            (investigation_id,),
        )
        hyp_rows = cur.fetchall()

    hypotheses = [
        {
            "rank": h[0], "pr_url": h[1], "pr_title": h[2],
            "pr_author": h[3],
            "pr_merged_at": h[4].isoformat() if h[4] else None,
            "file_path": h[5], "line_number": h[6], "diff_type": h[7],
            "confidence": float(h[8]) if h[8] is not None else None,
            "evidence": h[9],
            "narrative": inv.get("llm_narrative") if h[0] == 1 else None,
        }
        for h in hyp_rows
    ]

    return inv, hypotheses


@router.post("/reports/{investigation_id}")
async def generate_report(investigation_id: str, request: Request):
    """Generate and return a markdown report."""
    org_id = request.state.org_id
    conn = get_conn()
    try:
        set_org_context(conn, org_id)
        inv, hypotheses = _fetch_investigation_full(conn, org_id, investigation_id)
    finally:
        release_conn(conn)

    md = _build_markdown(inv, hypotheses)
    return {"investigation_id": investigation_id, "report": md}


@router.get("/reports/{investigation_id}/download")
async def download_report(investigation_id: str, request: Request):
    """Download investigation report as a .md file."""
    org_id = request.state.org_id
    conn = get_conn()
    try:
        set_org_context(conn, org_id)
        inv, hypotheses = _fetch_investigation_full(conn, org_id, investigation_id)
    finally:
        release_conn(conn)

    md = _build_markdown(inv, hypotheses)
    filename = f"bugpilot-{investigation_id}.md"
    return PlainTextResponse(
        content=md,
        media_type="text/markdown",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


@router.post("/reports/{investigation_id}/confluence")
async def push_to_confluence(
    investigation_id: str, req: ConfluenceRequest, request: Request
):
    """Push report to Confluence (requires confluence connector configured)."""
    org_id = request.state.org_id
    conn = get_conn()
    try:
        set_org_context(conn, org_id)
        inv, hypotheses = _fetch_investigation_full(conn, org_id, investigation_id)

        # Check for Confluence connector credentials
        with conn.cursor() as cur:
            cur.execute(
                "SELECT id FROM connectors WHERE org_id = %s AND type = 'confluence' LIMIT 1",
                (org_id,),
            )
            connector_row = cur.fetchone()
    finally:
        release_conn(conn)

    if not connector_row:
        raise HTTPException(
            status_code=400,
            detail="No Confluence connector configured. Run 'bugpilot connect confluence'.",
        )

    from backend.app.services.secrets import get_secret
    try:
        creds = get_secret(org_id, "confluence", "default")
    except KeyError:
        raise HTTPException(status_code=400, detail="Confluence credentials not found")

    md = _build_markdown(inv, hypotheses)
    title = req.title or f"BugPilot: {investigation_id} — {inv.get('service_name','')}"

    import httpx
    confluence_url = creds.get("url", "").rstrip("/")
    auth = (creds["username"], creds["api_token"])

    # Convert markdown to Confluence storage format (simplified XHTML)
    # In production use a proper MD→Confluence converter
    storage_value = f"<p><pre>{md}</pre></p>"

    payload = {
        "type": "page",
        "title": title,
        "space": {"key": req.space_key},
        "body": {
            "storage": {
                "value": storage_value,
                "representation": "storage",
            }
        },
    }
    if req.parent_page_id:
        payload["ancestors"] = [{"id": req.parent_page_id}]

    async with httpx.AsyncClient(auth=auth, timeout=30) as client:
        resp = await client.post(
            f"{confluence_url}/rest/api/content",
            json=payload,
        )

    if resp.status_code not in (200, 201):
        raise HTTPException(
            status_code=502,
            detail=f"Confluence error: {resp.status_code} {resp.text[:200]}",
        )

    page_data = resp.json()
    return {
        "status": "published",
        "confluence_url": f"{confluence_url}/pages/{page_data.get('id','')}",
        "page_id": page_data.get("id"),
    }
